### ISSUE TITLE
After composer install

### ISSUE THREAD

**Issue by devstevehowe** [laravel-enso/DataTable#5]
php artisan vendor:publish --tag=datatable-component

                                                               
  [Symfony\Component\Debug\Exception\FatalThrowableError]      
  Class 'LaravelEnso\DataTable\DataServiceProvider' not found

I have verified the folder is in the vendor directory

**Comment by aocneanu** [comment]
It seems that it was a mistake in the `readme.md` file . The correct name of the provider is
`LaravelEnso\DataTable\DataTableServiceProvider::class` and this is what you need to register in `config/app.php` file under the providers array.

I just updated the readme and regenerated the docs (https://docs.laravel-enso.com#datatable)

If you are using Sublime then try the provided snippet in order to create the table structure more easily. You will find it under the vendor/laravel-enso/datatable/snippets folder.
